---
# if true, will try to run the bts client inside a debugger
cmdline_debug: false

# activate the debug flag on the wsgi app
wsgi_debug: false

# the logging levels for the different submodules
# can be any of DEBUG, INFO, WARNING, ERROR
logging:
    bitshares_delegate_tools: DEBUG
    bitshares_delegate_tools.core: INFO
    bitshares_delegate_tools.rpcutils: INFO
    bitshares_delegate_tools.monitor: INFO
    bitshares_delegate_tools.notification: INFO
    bitshares_delegate_tools.feeds: INFO

cmdline:
    make_args: ['-j4']
    run_args: []

# in the 'nodes' variable you should specify the list of instances of the bitshares client
# you intend to run on this computer.
# Nodes can be of 3 types:
#  - seed nodes
#  - delegate nodes
#  - remote delegate nodes
#
# The choice of node type will tune a bit the interface and enable/disable
# functionality, such as feed publishing for delegates but not for seed nodes
#
# For each node you can specify which type of monitoring you want:
#  - feeds: checks price feeds, and optionally publish them if the node is a delegate
#  - email: send an email notification when client crashes or loses network connections
#  - apns: send an iOS push notification when client crashes or loses network connections
#
# Examples configs:
# nodes:
#     -
#         type: seed    # seed node type: no open wallet, high number of connections
#         name: seed01  # the name for this seed node. This is just for you, it serves no other purpose
#         rpc_port: 5678
#         rpc_user: username
#         rpc_password: secret-password
#         monitoring: [email]
#     -
#         type: delegate         # delegate node type: run a single delegate account
#         name: delegate1  # the name of the delegate. This needs to be an existing account
#         monitoring: [feeds,email]
#         # you can specify the bts data dir of the running client
#         # and it will fetch rpc connections params automatically
#         # this works for both seed nodes and delegate nodes
#         data_dir: ~/.BitSharesX
#
#     -
#         type: delegate
#         name: delegate2
#         monitoring: [feeds,email]
#         data_dir: ~/.BitSharesX
#     -
#         type: delegate    # remote delegate node type: access to a remote node's delegate info. You need to have ssh access to this node for this to work
#         name: delegate3  # the name for this remote node. This is just for you, it serves no other purpose
#         venv_path: ~/.virtualenvs/bitshares_delegate_tools # virtualenv dir in which the bts tools are installed on the remote machine
#         rpc_host: user@myhost  # hostname. Anything you can pass to "ssh" you can put here (eg: your aliases in ~/.ssh/config)
#         rpc_port: 5678
#         rpc_user: username
#         rpc_password: secret-password
#
nodes:
    -
        type: seed    # seed node type: no accounts, high number of connections
        name: seed01  # the name for this seed node. This is just for you, it serves no other purpose
        data_dir: ~/Library/Application Support/BitShares X
        monitoring: [email]

monitoring:
    monitor_time_interval: 5
    plots_time_span: 86400

    feeds:
        check_time_interval: 300
        publish_time_interval: 3600
        median_time_span: 3600

    email:
        smtp_server: smtp.example.com
        smtp_user: user
        smtp_password: secret-password
        identity: "BTS Monitor <bts_monitor@example.com>"
        recipient: me@example.com

    apns:
        cert: bts_apns.pem
        tokens: []



env:
    active: production

    development:
        git_repo: https://github.com/BitShares/bitshares_toolkit.git
        git_branch: develop

        linux:
            BITSHARES_HOME_DIR: ~/.BitSharesXTS
            BITSHARES_BUILD_DIR: ~/.BitSharesXTS_build
            BITSHARES_BIN_DIR: ~/.BitSharesXTS_bin

        darwin:
            BITSHARES_HOME_DIR: ~/Library/Application Support/BitShares XTS
            BITSHARES_BUILD_DIR: ~/.BitSharesXTS_build
            BITSHARES_BIN_DIR: ~/.BitSharesXTS_bin

    production:
        git_repo: https://github.com/dacsunlimited/bitsharesx.git
        git_branch: master

        linux:
            BITSHARES_HOME_DIR: ~/.BitSharesX
            BITSHARES_BUILD_DIR: ~/.BitSharesX_build
            BITSHARES_BIN_DIR: ~/.BitSharesX_bin

        darwin:
            BITSHARES_HOME_DIR: ~/Library/Application Support/BitShares X
            BITSHARES_BUILD_DIR: ~/.BitSharesX_build
            BITSHARES_BIN_DIR: ~/.BitSharesX_bin

    keyid:
        git_repo: https://github.com/keyid/keyid.git
        git_branch: master

        linux:
            BITSHARES_HOME_DIR: ~/.KeyID
            BITSHARES_BUILD_DIR: ~/.KeyID_build
            BITSHARES_BIN_DIR: ~/.KeyID_bin

        darwin:
            BITSHARES_HOME_DIR: ~/Library/Application Support/KeyID
            BITSHARES_BUILD_DIR: ~/.KeyID_build
            BITSHARES_BIN_DIR: ~/.KeyID_bin






