---
# Config file containing the build, run and monitor environments and
# other configuration variables
#
# This file should contain sensible default values in as many places as
# possible, but you will have to at least specify your own values in the
# following categories:
#  - run_environments [for the cmdline tool]
#  - nodes            [for the monitoring webapp]
#
# For a more detailed description of the format of this file, visit:
# https://bts-tools.readthedocs.org/en/latest/config_format.html
#

logging:
    bts_tools.feeds: DEBUG

# flags to be passed to make; shared among all build environments
make_args: ['-j4']

#
# list of nodes (delegate accounts / seed nodes) that are being monitored
#
nodes:
    -
        client: bts2
        type: delegate
        name: my_witness_name
        #monitoring: [feeds]
        witness_host: localhost
        witness_port: 8090
        witness_user: myuser          # defined in api_access.json
        witness_password: mypassword  # defined in api_access.json
        wallet_host: localhost
        wallet_port: 8093

#
# configuration of the monitoring plugins
#
monitoring:
    seed:
        desired_number_of_connections: 200
        maximum_number_of_connections: 400

    feeds:
        check_time_interval: 300
        median_time_span: 1800
        #publish_time_interval: 2400         # use this to publish feeds at fixed time intervals (in seconds)
        publish_time_slot: 0                # use this to publish every hour at a fixed number of minutes (in minutes)
        feed_providers: [Poloniex, CCEDK, Btc38, Yunbi,  # BTS valuation
                         Yahoo, Google, Bloomberg]       # market indices

#
# configuration of the notification types
#
notification:
    email:
        smtp_server: smtp.example.com
        smtp_user: user
        smtp_password: secret-password
        identity: "BTS Monitor <bts_monitor@example.com>"
        recipient: me@example.com

    boxcar:
        tokens: []
