hostname: &hostname xxxxxxxx
domain: xxxxxxxx.xxx

vps:
    # config for vultr provider
    vultr:
        api_key: xxxxxxxx
        name: *hostname
        location: amsterdam
        vps_plan: 4G     # can be: 1G, 2G, 4G, etc.
        os_id: 193       # Debian 8 x64 (Jessie)
        ssh_keys: [xxxxxxxx, xxxxxxxx]  # need to have at least the ssh key from the host performing the installation

    # config for gandi provider
    gandi:
        api_key: xxxxxxxx
        name: *hostname
        location: paris
        cores: 4
        memory: 8192  # in MB
        disk_size: 81920  # in MB
        src_disk_id: 3315704 # Debian 8 64 bits (HVM)
        ssh_keys: [graphene, brannigan]

# if true, the graphene client will be built directly on the new node,
# otherwise it gets deployed from the host currently running the install
compile_on_new_host: true

unix_hostname: *hostname
unix_user: xxxxxxxx
unix_password: xxxxxxxx

# additional keys to be installed in .ssh/authorized_keys for both root and normal user
#ssh_keys:
#- ssh-rsa xxxxxxxx
#- ssh-rsa xxxxxxxx

# TODO: make this optional
git_name: xxxxxxxx
git_email: xxxxxxxx

# access to witness restricted APIs, used to create api_access.json
witness_api_access:
    user: &witness_user xxxxxxxx
    password: &witness_password xxxxxxxx

# config.yaml variables
config_yaml:
    make_args: ['-j2']
    clients:
        bts:
            type: bts
            data_dir: ~/.BitShares2_seed
            api_access: ~/api_access.json
            witness_host: localhost
            witness_port: 8090
            witness_user: *witness_user
            witness_password: *witness_password
            wallet_host: localhost
            wallet_port: 8093
            roles:
            -
                role: seed
                name: *hostname
            #deploy:  # params only needed when deploying a new instance, will not end up in the final config.yaml file
            #    blockchain_snapshot: ~/.BitShares2

        muse:
            type: muse
            data_dir: ~/.Muse_seed
            api_access: ~/api_access.json
            witness_user: *witness_user
            witness_password: *witness_password
            roles:
            -
                role: seed
                name: *hostname
            #deploy:  # params only needed when deploying a new instance, will not end up in the final config.yaml file
            #    blockchain_snapshot: ~/.Muse

        steem:
            type: steem
            data_dir: ~/.Steem_seed
            api_access: ~/api_access.steem.json
            run_cli_args: ['--rpc-http-allowip', '127.0.0.1']
            seed_nodes: ['54.186.215.133:2001', '45.32.66.168:2001']
            witness_host: localhost
            witness_port: 8490
            witness_user: *witness_user
            witness_password: *witness_password
            wallet_host: localhost
            wallet_port: 8493
            roles:
            -
                role: seed
                name: *hostname
            #deploy:  # params only needed when deploying a new instance, will not end up in the final config.yaml file
            #    blockchain_snapshot: ~/.Steem

    notification:
        email:
            smtp_server: smtp.example.com
            smtp_user: user
            smtp_password: secret-password
            identity: "BTS Monitor <bts_monitor@example.com>"
            recipient: me@example.com

        boxcar:
            tokens: []
